- name: Copy Elastic Repo File
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install FileBeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copy Filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Restart Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes